import 'package:flutter/foundation.dart';

import '../../learning/model/exam.dart';
import '../../learning/model/exam_attempt.dart';
import '../../learning/model/course_repository.dart';
import '../../learning/model/exam_attempt_repository.dart';
import '../../learning/view/i_exam_view.dart';

/// Coordinates between the exam UI and the repositories.
///
/// Responsible for loading the exam, evaluating answers, saving attempts,
/// and preventing duplicate submissions.
class ExamPresenter {
  final CourseRepository _courseRepository;
  final ExamAttemptRepository _examAttemptRepository;
  final String _userId;

  IExamView? _view;
  Exam? _exam;

  bool _isSubmitting = false;
  bool _attemptSaved = false;

  ExamPresenter({
    required CourseRepository courseRepo,
    required ExamAttemptRepository examAttemptRepo,
    required String userId,
  })  : _courseRepository = courseRepo,
        _examAttemptRepository = examAttemptRepo,
        _userId = userId;

  /// Attaches the view that will receive UI updates.
  set view(IExamView? view) {
    _view = view;
  }

  // ---------------------------------------------------------------------------
  // 1. Load exam (examId corresponds to a course identifier)
  // ---------------------------------------------------------------------------
  Future<void> loadExam(String examId) async {
    debugPrint('[PRESENTER][EXAM] Loading exam');
    _view?.showLoading(true);

    try {
      final exam = await _courseRepository.getExam(examId);
      if (exam == null) {
        _view?.showError('Exam not found.');
        return;
      }

      _exam = exam;
      _attemptSaved = false;
      _isSubmitting = false;

      _view?.showExam(exam);
      debugPrint('[PRESENTER][EXAM] Exam loaded');
    } catch (e) {
      debugPrint('[PRESENTER][EXAM] Exam loading failed');
      _view?.showError('Unable to load exam. Please try again.');
    } finally {
      _view?.showLoading(false);
    }
  }

  // ---------------------------------------------------------------------------
  // 2. Navigate to a specific question (index)
  // ---------------------------------------------------------------------------
  void showQuestion(int index) {
    if (_exam == null || index < 0 || index >= _exam!.questions.length) return;
    _view?.showQuestion(index);
  }

  // ---------------------------------------------------------------------------
  // 3. Submit exam answers
  // ---------------------------------------------------------------------------
  Future<void> submitExam(Map<int, dynamic> answers) async {
    // Guard against duplicate submissions
    if (_exam == null || _isSubmitting || _attemptSaved) return;

    debugPrint('[PRESENTER][EXAM] Exam submission started');
    _isSubmitting = true;

    try {
      final (score, passed) = _evaluateAnswers(answers);

      debugPrint('[PRESENTER][EXAM] Exam result calculated');

      final attempt = ExamAttempt(
        id: '', // generated by the database
        userId: _userId,
        examId: _exam!.id,
        score: score,
        passed: passed,
        attemptedAt: DateTime.now(),
      );

      debugPrint('[REPOSITORY][EXAM] Saving attempt');
      final savedAttempt = await _examAttemptRepository.saveAttempt(attempt);
      _attemptSaved = true;

      debugPrint('[PRESENTER][EXAM] Exam submission completed');
      _view?.showResult(savedAttempt);
    } catch (e) {
      debugPrint('[PRESENTER][EXAM] Exam submission failed');
      _view?.showError('Failed to save exam attempt. Please try again.');
    } finally {
      _isSubmitting = false;
    }
  }

  // ---------------------------------------------------------------------------
  // 4. Navigate after exam completion
  // ---------------------------------------------------------------------------
  void navigateAfterExam() {
    _view?.navigateAfterExam();
  }

  // ---------------------------------------------------------------------------
  // Private helpers
  // ---------------------------------------------------------------------------

  /// Evaluates the answers and returns the score (as a ratio) and a boolean
  /// indicating whether the exam was passed.
  (double, bool) _evaluateAnswers(Map<int, dynamic> answers) {
    final questions = _exam!.questions;
    double totalPoints = 0;
    double earnedPoints = 0;

    for (int i = 0; i < questions.length; i++) {
      final q = questions[i];
      final points = (q.points ?? 1).toDouble();
      totalPoints += points;

      final userAnswer = answers[i];
      if (_isAnswerCorrect(q, userAnswer)) {
        earnedPoints += points;
      }
    }

    final double score = totalPoints > 0 ? earnedPoints / totalPoints : 0;
    final double passingThreshold = _exam!.passingScore ?? 0.6;
    final bool passed = score >= passingThreshold;

    return (score, passed);
  }

  /// Checks whether the given [userAnswer] matches the correct answer
  /// defined in the [question].
  bool _isAnswerCorrect(ExamQuestion question, dynamic userAnswer) {
    final correct = question.correctAnswer;
    final userStr = userAnswer?.toString().trim().toLowerCase() ?? '';
    final correctStr = correct?.toString().trim().toLowerCase() ?? '';

    // Handle multiple acceptable answers.
    if (correct is List) {
      return correct.any(
          (item) => item.toString().trim().toLowerCase() == userStr);
    }

    return userStr == correctStr;
  }
}