import 'package:flutter/foundation.dart';

import '../../../core/services/supabase_service.dart';
import 'progress.dart';
import 'progress_repository.dart';

/// Concrete implementation of [ProgressRepository] using Supabase.
///
/// Interacts with the `progress` table.
class ProgressRepositorySupabase implements ProgressRepository {
  final SupabaseService _supabaseService;

  ProgressRepositorySupabase(this._supabaseService);

  // ---------------------------------------------------------------------------
  // getProgress
  // ---------------------------------------------------------------------------
  @override
  Future<Progress?> getProgress(String userId, String courseId) async {
    debugPrint('[REPOSITORY][PROGRESS] Loading user progress');
    debugPrint('[DB] Progress query started');

    try {
      final response = await _supabaseService.client
          .from('progress')
          .select()
          .eq('user_id', userId)
          .eq('course_id', courseId)
          .maybeSingle();

      debugPrint('[DB] Progress query completed');

      if (response == null) {
        debugPrint('[REPOSITORY][PROGRESS] No progress found');
        return null;
      }

      debugPrint('[REPOSITORY][PROGRESS] Progress loaded');
      return Progress.fromMap(response);
    } catch (e) {
      debugPrint('[ERROR][PROGRESS] Failed to load progress');
      debugPrint('Reason: $e');
      rethrow;
    }
  }

  // ---------------------------------------------------------------------------
  // markLessonCompleted
  // ---------------------------------------------------------------------------
  @override
  Future<void> markLessonCompleted(
      String userId, String courseId, String lessonId) async {
    debugPrint('[REPOSITORY][PROGRESS] Marking lesson completed');
    debugPrint('[DB] Progress write started');

    try {
      // 1. Fetch existing progress record (if any)
      final existing = await _supabaseService.client
          .from('progress')
          .select()
          .eq('user_id', userId)
          .eq('course_id', courseId)
          .maybeSingle();

      final now = DateTime.now().toIso8601String();
      List<String> completed = [];

      if (existing != null) {
        // Start from existing completed list
        completed = (existing['completed_lesson_ids'] as List<dynamic>?)
                ?.map((e) => e.toString())
                .toList() ??
            [];
      }

      // Only add if not already present
      if (!completed.contains(lessonId)) {
        completed.add(lessonId);
      }

      final data = {
        'user_id': userId,
        'course_id': courseId,
        'completed_lesson_ids': completed,
        'last_accessed': now,
      };

      if (existing != null) {
        // Update the existing record
        await _supabaseService.client
            .from('progress')
            .update(data)
            .eq('id', existing['id'] as String);
      } else {
        // Insert a new record (id will be generated by the DB)
        await _supabaseService.client.from('progress').insert(data);
      }

      debugPrint('[DB] Progress write completed');
    } catch (e) {
      debugPrint('[ERROR][PROGRESS] Failed to mark lesson completed');
      debugPrint('Reason: $e');
      rethrow;
    }
  }

  // ---------------------------------------------------------------------------
  // getCompletedLessons
  // ---------------------------------------------------------------------------
  @override
  Future<List<String>> getCompletedLessons(
      String userId, String courseId) async {
    final progress = await getProgress(userId, courseId);
    return progress?.completedLessonIds ?? [];
  }

  // ---------------------------------------------------------------------------
  // saveProgress
  // ---------------------------------------------------------------------------
  @override
  Future<void> saveProgress(Progress progress) async {
    debugPrint('[REPOSITORY][PROGRESS] Saving progress');
    debugPrint('[DB] Progress write started');

    try {
      final data = progress.toMap();
      // Upsert based on primary key 'id' if present.
      // We'll use .upsert() with the record's id, which will insert if not exist
      // or update if the id matches.
      await _supabaseService.client.from('progress').upsert(data);

      debugPrint('[DB] Progress write completed');
    } catch (e) {
      debugPrint('[ERROR][PROGRESS] Failed to save progress');
      debugPrint('Reason: $e');
      rethrow;
    }
  }
}