/// Pure data model representing an in-app notification.
///
/// Notifications are generated by system events (e.g., a tutor submitting a
/// course) and are typically consumed by admins. This model holds the
/// notification data; delivery and persistence are handled by the repository
/// layer.
class Notification {
  /// Unique identifier for the notification.
  final String id;

  /// The user ID of the recipient (usually an admin).
  final String recipientId;

  /// Short title or subject.
  final String title;

  /// Detailed body text.
  final String body;

  /// Whether the notification has been read by the recipient.
  final bool isRead;

  /// Optional type/category (e.g., `'course_submission'`, `'system'`).
  final String? type;

  /// Timestamp when the notification was created.
  final DateTime createdAt;

  const Notification({
    required this.id,
    required this.recipientId,
    required this.title,
    required this.body,
    this.isRead = false,
    this.type,
    required this.createdAt,
  });

  // ---------------------------------------------------------------------------
  // Factory & serialization
  // ---------------------------------------------------------------------------

  factory Notification.fromMap(Map<String, dynamic> map) {
    return Notification(
      id: map['id'] as String,
      recipientId: map['recipient_id'] as String,
      title: map['title'] as String,
      body: map['body'] as String,
      isRead: map['is_read'] as bool? ?? false,
      type: map['type'] as String?,
      createdAt: DateTime.parse(map['created_at'] as String),
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'recipient_id': recipientId,
      'title': title,
      'body': body,
      'is_read': isRead,
      'type': type,
      'created_at': createdAt.toIso8601String(),
    };
  }

  // ---------------------------------------------------------------------------
  // Convenience
  // ---------------------------------------------------------------------------

  /// Returns a copy with the `isRead` flag updated.
  Notification markAsRead() {
    return copyWith(isRead: true);
  }

  Notification copyWith({
    String? id,
    String? recipientId,
    String? title,
    String? body,
    bool? isRead,
    String? type,
    DateTime? createdAt,
  }) {
    return Notification(
      id: id ?? this.id,
      recipientId: recipientId ?? this.recipientId,
      title: title ?? this.title,
      body: body ?? this.body,
      isRead: isRead ?? this.isRead,
      type: type ?? this.type,
      createdAt: createdAt ?? this.createdAt,
    );
  }

  // ---------------------------------------------------------------------------
  // Equality & debug
  // ---------------------------------------------------------------------------

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Notification &&
          runtimeType == other.runtimeType &&
          id == other.id;

  @override
  int get hashCode => id.hashCode;

  @override
  String toString() =>
      'Notification(id: $id, recipientId: $recipientId, '
      'title: $title, isRead: $isRead, type: $type, createdAt: $createdAt)';
}